# Railway configuration file

# Environment variables
[variables]
NODE_VERSION = "20"
NIXPACKS_NODE_VERSION = "20"

# Build configuration
[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

# Deploy configuration
[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "node ./dist/server/entry.mjs"
sleepApplication = false
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
