# Railway configuration file

# Environment variables
[variables]
NODE_VERSION = "18.20.8"
NIXPACKS_NODE_VERSION = "18.20.8"

# Build configuration
[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

# Deploy configuration
[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "npm start"
sleepApplication = false
healthcheckPath = "/"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10