[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
# Install dependencies using the lockfile for reproducible builds
cmds = ["npm ci"]

[phases.build]
cmds = [npm run build]

[start]
cmd = "npm start"
