[build]
builder = "NIXPACKS"
nixpacksConfigPath = ".nixpacks.toml"

[start]
cmd = "npm start"

[env]
STRIPE_SECRET = "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"
PREMIUM_PRICE_ID = "price_1RSCWZFlLCnouIYKzXblyW54"
PREMIUM_TOKEN_SECRET = "9e21cb497ba8cbd3b64f94b554de7b4438ed7a990c9885b2263598f710ca9440"
BASE_URL = "http://pleco-xa.com"
